"""create account and transaction table

Revision ID: a01f6c4908aa
Revises:
Create Date: 2026-05-30 00:50:56.221553

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a01f6c4908aa"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conta",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "tipo",
            sa.Enum("DEBITO", "CREDITO", "FINANCIAMENTO", name="tipocontaenum"),
            nullable=False,
        ),
        sa.Column("limite_ou_total", sa.Float(), nullable=True),
        sa.Column("dia_fechamento", sa.Integer(), nullable=True),
        sa.Column("dia_vencimento", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "transacao",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("grupo_id", sa.Integer(), nullable=True),
        sa.Column("descricao", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("valor", sa.Float(), nullable=False),
        sa.Column("data", sa.Date(), nullable=False),
        sa.Column("paga", sa.Boolean(), nullable=False),
        sa.Column("fatura_mes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "categoria",
            sa.Enum(
                "MORADIA",
                "ALIMENTACAO",
                "TRANSPORTE",
                "LAZER",
                "SAUDE",
                "REFEICAO",
                "EDUCACAO",
                "VESTUARIO",
                "JOGO",
                "TECNOLOGIA",
                "PROFISSIONAL",
                "VEICULO",
                "SERVICO",
                "SERVICO_ONLINE",
                "PET",
                "FERIAS",
                "VIAGEM",
                "FAMILIA",
                "ELETRONICO",
                "MERCADO",
                "CAFE",
                "DELIVERY",
                "PRESENTE",
                "REFEICAO_TRABALHO",
                "TAG_VEICULO",
                "TRABALHO",
                "OUTROS",
                name="categoriatransacaoenum",
            ),
            nullable=False,
        ),
        sa.Column("conta_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conta_id"],
            ["conta.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transacao_grupo_id"), "transacao", ["grupo_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transacao_grupo_id"), table_name="transacao")
    op.drop_table("transacao")
    op.drop_table("conta")
    # ### end Alembic commands ###
