from enum import StrEnum


# Novas categorias para classificar os gastos
class CategoriaTransacaoEnum(StrEnum):
    MORADIA = "moradia"
    ALIMENTACAO = "alimentacao"
    TRANSPORTE = "transporte"
    LAZER = "lazer"
    SAUDE = "saude"
    REFEICAO = "refeicao"
    EDUCACAO = "educacao"
    VESTUARIO = "vestuario"
    JOGO = "jogo"
    TECNOLOGIA = "tecnologia"
    PROFISSIONAL = "profissional"
    VEICULO = "veiculo"
    SERVICO = "servico"
    SERVICO_ONLINE = "servico_online"
    PET = "pet"
    FERIAS = "ferias"
    VIAGEM = "viagem"
    FAMILIA = "familia"
    ELETRONICO = "eletronico"
    MERCADO = "mercado"
    CAFE = "cafe"
    DELIVERY = "delivery"
    PRESENTE = "presente"
    REFEICAO_TRABALHO = "refeicao_trabalho"
    TAG_VEICULO = "tag_veiculo"
    TRABALHO = "trabalho"
    OUTROS = "outros"
